query getScraps { 
	scraps(order_by: {created_at: desc}) {
		id
		title
		created_at
	}
}

query getScrapById($id: Int!) {
	scraps_by_pk(id: $id) {
		id
		title
		created_at
	}
}

mutation createScrap($title: String) {
	insert_scraps_one(object: {title: $title}){
		id
		title
		created_at
	}
}


