query getScraps { 
	scraps(order_by: {created_at: desc}) {
		id
		title
		created_at
		comments_aggregate {
			aggregate {
				count
			}
		}
	}
}

query getScrapById($id: Int!) {
	scraps_by_pk(id: $id) {
		id
		title
		created_at
		comments {
			id
			body
			created_at
		}
	}
}

mutation createScrap($title: String!) {
	insert_scraps_one(object: {title: $title}){
		id
		title
		created_at
	}
}

mutation editScrapTitle($id: Int!, $title: String) {
	update_scraps_by_pk(pk_columns: {id: $id}, _set: {title: $title}) {
    id
  }
}

mutation createComment($scrapId: Int!, $body: String!) {
	insert_comments_one(object: {scrap_id: $scrapId, body: $body}) {
		id
		body
		created_at
	}
}

mutation deleteScrap($id: Int!) {
	delete_scraps_by_pk(id: $id) {
		id
	}
}

